language: node_js

node_js:
  - "10.16.0"

env:
  - NODE_ENV=travis
  - MOZ_HEADLESS=1

branches:
  only:
    - master

addons:
  firefox: latest

install: npm install

# before_script:
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - sleep 3

script: npm run test:travis
