language: node_js

node_js:
  - "10.16.0"

env:
  - NODE_ENV=travis
  - MOZ_HEADLESS=1

branches:
  only:
    - master

addons:
  firefox: latest

install: npm install

services:
  - xvfb

script: npm run test:travis
